### ISSUE TITLE
Time out if input is received while tests are running

### ISSUE THREAD

**Issue by ppraisethesun** [influxdata/mix_test_interactive#43]
```
** (exit) exited in: GenServer.call(MixTestInteractive.InteractiveMode, {:command, "\n"}, 5000)
    ** (EXIT) time out
    (elixir 1.11.3) lib/gen_server.ex:1027: GenServer.call/3
    (mix_test_interactive 1.0.0) lib/mix_test_interactive.ex:23: MixTestInteractive.loop/0
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.3) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

Steps to reproduce: 
* mix test.interactive
* press enter while tests are running, and if it takes more than 5 seconds, task exits

**Comment by randycoulman** [comment]
Ah, good catch, thanks! Looks like I missed a case where an `:infinite` timeout is needed. Will get this fixed later this week.

**Comment by randycoulman** [comment]
Release in v1.0.1. Thanks for the report!
